# Generated by Django 4.2.1 on 2023-05-16 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('event', models.CharField(blank=True, max_length=200)),
                ('problem', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('missed', 'Missed'), ('doing', 'Doing'), ('finished', 'Finished'), ('canceled', 'Canceled'), ('changed', 'Changed')], default='doing', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('financial_help', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_tasks', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
