# Generated by Django 4.2.1 on 2023-05-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('director', 'Director'), ('manager', 'Manager'), ('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=15),
        ),
    ]
